sudo: required
services:
  - docker

before_install:
  - docker build -f MugBot/Dockerfile -t promofaux/mugbot .    
script:
  - docker images promofaux/mugbot
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "development" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag promofaux/mugbot promofaux/mugbot:development;
    docker push promofaux/mugbot:development;
    fi