version: '3.4'

services:
  mugbot:
    image: ${DOCKER_REGISTRY-}mugbot
    container_name: mugbot
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    build:
      context: .
      dockerfile: MugBot/Dockerfile
