version: '3'

services:
  mugbot:
    image: mugbot
    container_name: mugbot
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
    build:
      context: .
      dockerfile: MugBot/Dockerfile
